### PR TITLE
Fixed issues with https 

### PR DESCRIPTION
**Pull request by magestican**

### CODE REVIEW

**Comment by ealves** [comment]
It doesn't work.

**Comment by phamdt** [comment]
Perhaps you can add steps to reproduce in case some one wants to help troubleshoot

**Comment by magestican** [comment]
@ealves what do you mean it doesnt work? Do you get an error? Are you testing on chrome? If so you need to update your webdriver version. This is working fine for me and my team of 5 testers at my company. Please let me know what issues you are having so we can merge this.

**Comment by JamesWebDev** [comment]
2 thoughts, is the doesn't work issue the result of globally installed npm packages @ealves?  Also, @magestican I see you switched the express file to https, but do http sites  still work, or does it now only work for https

**Comment by ealves** [comment]
Well, after I update my environment with your PR I updated everything else. I executed npm and bower install too.

My environment versions:

Ubuntu 16.04;
Chrome 58.0.3029.81;
Webdriver-manager 12.0.5;
Protractor 5.1.1;
NPM 3.10.10
NodeJs 6.10.2

Console log errors:

`GET https://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_CLOSED`

`Mixed Content: The page at 'https://localhost:3002/app/#/conf' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:4444/wd/hub/'. This request has been blocked; the content must be served over HTTPS.`

Please describe what steps do you did to get this working @magestican.

No @JamesWebDev, I think it's not a problem with my installed npm packages globally or not.

**Comment by magestican** [comment]
Hey @ealves and everyone else, sorry for the delay. 

Today I just run into the issue all of you are experiencing, openssl is required to run the protractor recorder server since it auto generates ssl certificates to run over https.

The reason there were no console errors is because I was not logging the errors to console, I have updated the PR so it will.

I have also updated the readme.md file with instructions about using openssl and added an entry to advise people who have issues running protractor recorder on versions of chrome 58+

This should be all that's needed, thank you!

**Comment by ealves** [comment]
Hey there, I am still getting errors both on Linux and Windows…
 
I don’t know if a have to generate certificates with openssl, but no errors was thrown about pem or certs when executed ‘gulp’.
 
So after running everything through cmd or terminal I try navigate to https://localhost:3002/app and it shows a popup:
 
‘_Selenium is not running
Please, run Selenium with Webdriver Manager: "webdriver-manager start_"’.
 
This popup only disappear if I accept the browser to load unsafe scripts. Browser shows one button on top, right beside favorite icon in the url input:
 
‘_This page is trying to load scripts from unauthenticated sources.
Load unsafe scripts_’
 
Please, we need more details. I suggest you try to run this on a fresh Unix/Windows environments.
Thanks @magestican

**Comment by magestican** [comment]
Well as unsafe as this sounds, you are almost done, the message comes up because the protractor server is using a self signed certificate to run over https, no other reason. 

If you accept the message that says  "load unsafe scripts" you then just have to reload and you can start recording and playing back recordings on any https site.

I am afraid that this is the side effect of my solution.

**Comment by JamesWebDev** [comment]
I've not messed with protractors ssl before, but when I'm using iis I just install my cert in the trusted cert store for the box to avoid those kind of warnings

**Comment by JamesWebDev** [comment]
Easy to do from IE (said no one ever?)if your on Windows something close to this should still work https://conetrix.com/Blog/how-to-trust-a-self-signed-certificate-in-ie-9

**Comment by JamesWebDev** [comment]
@magestican, I cloned your branch, installed openssl, added it to my system path, and I did the "load unsafe scripts" and reloaded, but it won't let me record.

**Comment by magestican** [comment]
Were you running webdriver on a console somewhere? I will make a video of
this and upload it..people have been using it here at work for a few months
already so shouldnt be a problem.

If you are running tests on chrome you need to use the latest version of
the chrome driver and specify that manually on your webdriver start

webdriver-manager update --versions.chrome=2.31 //this will install the
latest version of webdriver
webdriver-manager start --versions.chrome=2.31 //this will run webdriver
with the proper version, you would think that webdriver will use the latest
version available but it doesnt, you need to specify that manually.

2017-07-26 12:25 GMT+10:00 James F <notifications@github.com>:

**Pull request closed without merging**
